### PR TITLE
ESNOOK-17-Create-platform-repository

### PR DESCRIPTION
**Pull request by Dan1m4D**
## What has been done?

- [x] Create nextjs project
- [x] Install dependencies

### CODE REVIEW

**Comment by Dan1m4D** [comment]
For now the project has tailwind, react-query, zustand, next-auth and nextui as added dependencies. If needed in the future we'll add more as needed 👌.

**Review by fungame2270 — APPROVED** [review]
Tested locally working as expected.
LGTM

**Review by fungame2270 — APPROVED** [review]
lgtm

**Review by fungame2270 — APPROVED** [review]
lgtm

**Review by RafaelCintaFerreira — APPROVED** [review]
Lgtm

**Review by fungame2270 — APPROVED** [review]
lgtm

**Review by RafaelCintaFerreira — APPROVED** [review]
Still LGMT

**Pull request merged**
